package paqueteproducto;

import java.util.Scanner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class pnl_Propuesto extends javax.swing.JPanel {

    /**
     * Variables que se pueden modificar
     */
    Scanner input = new Scanner(System.in);
    private final int tamañoPilaCola = 5;
    private int itr;
    String[] cola = {"15", "11", "9", "6", "1"};
    String[] pila = {"b", "a", "z", "y", "x"};
    Pila p;
    Cola c;
    String mostrarNotInf;
    private final DefaultTableModel tablaModeloPila = new DefaultTableModel();
    private final DefaultTableModel tablaModeloCola = new DefaultTableModel();

    /**
     * Creates new form pnl_Propuesto
     */
    public pnl_Propuesto() {
        
        menuValoresPreestablecidos();
        llenarTablaModeloPila();
        llenarTablaModeloCola();

        initComponents();
        editarIndicadorPilaCola();
    }

    /**
     * Métodos que se pueden modificar
     */
    private void llenarIndiceTablaModelo(DefaultTableModel tablaIndice) {
        tablaIndice.addColumn("Índice");
        for (int i = 0; i < tamañoPilaCola; i++) {
            tablaIndice.addColumn(String.valueOf(i));
        }
    }

    private void llenarTablaModeloPila() {
        llenarIndiceTablaModelo(tablaModeloPila); // se llena el índice

        String[] pilaTabla = new String[tamañoPilaCola + 1]; 
        pilaTabla[0] = "Pila";
        System.arraycopy(pila, 0, pilaTabla, 1, pila.length);
        tablaModeloPila.addRow(pilaTabla); // datos en la tabla
        
        // se pone el string de la pila
        p = new Pila(pila, 4);
    }

    private void llenarTablaModeloCola() {
        llenarIndiceTablaModelo(tablaModeloCola);

        String[] colaTabla = new String[tamañoPilaCola + 1];
        colaTabla[0] = "Cola";
        System.arraycopy(cola, 0, colaTabla, 1, cola.length);
        tablaModeloCola.addRow(colaTabla);
        
        c = new Cola(cola, 4, 0);
    }

    private void editarIndicadorPilaCola() {
        lbl_Fondo.setText("Fondo: " + p.getFondo());
        lbl_Tope.setText("Tope: " + p.getTope());
        
        lbl_Frente.setText("Frente: " + c.getFrente());
        lbl_Final.setText("Final: " + c.getFin());
        
    }
    //

    private void menuValoresPreestablecidos() {
        llenarTablaModeloPila();
        llenarTablaModeloCola();

        // se crea los obejtos de la clase Cola y Pila
        Cola c = new Cola(cola, 4, 0);
        Pila p = new Pila(pila, 4);

        mostrarNotInf = transformacion(c, p, 5, 1, 1);
    }

    private String transformacion(Cola c, Pila p, int longitud, int tipOp, int tipExp) {
        String notInf = "";
        String x, exp; // para almacenar el valor que retorna la cola al hacer la supresión

        switch (tipExp) {
            case 1 -> { // 15*x
                for (int i = 0; i < longitud; i++) {
                    x = c.suprimir();
                    notInf += (!x.equals("1") ? x + "*" : "");
                    notInf += p.pop(); // se hace pop y se disminuye en 1 el tope
                    notInf += ((p.getTope() > 0) ? "^" + (p.getTope() + 1) : ""); // por eso se suma 1 al tope
                    notInf += ((i < longitud - 1) ? operador(tipOp) : "");
                }
            }
            case 2 -> {
                for (int i = 0; i < longitud; i++) {
                    x = c.suprimir();
                    notInf += (!x.equals("1") ? x + "*" : "");
                    notInf += p.pop();
                    System.out.print("Ingrese el exponente n°" + (1 + i) + ": ");
                    exp = input.next();
                    notInf += (!exp.equals("1") ? "^" + exp : "");
                    notInf += ((i < longitud - 1) ? operador(tipOp) : "");
                }
            }
            case 3 -> {

            }
            default -> {
                System.out.println("\nError, opción no encontrada.\n");
            }
        }

        return "\n" + notInf + "\n";
    }

    private String operador(int tipOp) {
        String operador = "";

        switch (tipOp) {
            case 1 -> {
                operador = (itr % 2 == 0) ? "-" : "+";
                itr++;
            }
            case 2 -> {
                operador = (Math.round((Math.random() + 1)) == 1) ? "-" : "+";
            }
            case 3 -> {
                System.out.print("Indroduzca el operador n°" + (1 + itr) + ": ");
                operador = String.valueOf(input.next().charAt(0));
                itr++; // sirve para contar los operadores también.
            }
        }
        return operador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtArea_Enunciado = new javax.swing.JTextArea();
        txtFld_NotacionInfija = new javax.swing.JTextField();
        btn_Mostrar = new javax.swing.JButton();
        scrll_TablaPila = new javax.swing.JScrollPane();
        tbl_Pila = new javax.swing.JTable();
        scrll_TablaCola = new javax.swing.JScrollPane();
        tbl_Cola = new javax.swing.JTable();
        lbl_Fondo = new javax.swing.JLabel();
        lbl_Tope = new javax.swing.JLabel();
        lbl_Frente = new javax.swing.JLabel();
        lbl_Final = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDoubleBuffered(false);
        setEnabled(false);
        setFocusable(false);
        setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Enunciado");

        txtArea_Enunciado.setEditable(false);
        txtArea_Enunciado.setBackground(new java.awt.Color(255, 255, 255));
        txtArea_Enunciado.setColumns(20);
        txtArea_Enunciado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtArea_Enunciado.setLineWrap(true);
        txtArea_Enunciado.setRows(5);
        txtArea_Enunciado.setText("Se tiene dos Estructuras de datos, PILA que contiene una lista de variables y COLA que contiene una lista de coeficientes. Debe preparar un método que empleando las operaciones de PILAS Y COLAS, arme el POLINOMIO (cadena lineal) correspondiente en notación infija. Implementación: (a) En una sola clase main, (b) En una clase main con métodos en esa misma clase, (c) en una clase main con métodos en otra clase y (d) con Swing.");
        txtArea_Enunciado.setWrapStyleWord(true);
        txtArea_Enunciado.setAutoscrolls(false);
        txtArea_Enunciado.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtArea_Enunciado.setFocusable(false);
        txtArea_Enunciado.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtArea_Enunciado.setMinimumSize(new java.awt.Dimension(750, 110));

        txtFld_NotacionInfija.setColumns(45);
        txtFld_NotacionInfija.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_Mostrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Mostrar.setText("MOSTRAR");
        btn_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MostrarActionPerformed(evt);
            }
        });

        scrll_TablaPila.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrll_TablaPila.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrll_TablaPila.setAutoscrolls(true);

        tbl_Pila.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_Pila.setModel(tablaModeloPila);
        tbl_Pila.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbl_Pila.setAutoscrolls(false);
        tbl_Pila.setEnabled(false);
        tbl_Pila.setFocusable(false);
        tbl_Pila.setRequestFocusEnabled(false);
        tbl_Pila.setRowHeight(40);
        tbl_Pila.setRowSelectionAllowed(false);
        scrll_TablaPila.setViewportView(tbl_Pila);

        scrll_TablaCola.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrll_TablaCola.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tbl_Cola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_Cola.setModel(tablaModeloCola);
        tbl_Cola.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbl_Cola.setEnabled(false);
        tbl_Cola.setFocusable(false);
        tbl_Cola.setRequestFocusEnabled(false);
        tbl_Cola.setRowHeight(40);
        tbl_Cola.setRowSelectionAllowed(false);
        scrll_TablaCola.setViewportView(tbl_Cola);

        lbl_Fondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Fondo.setText("Fondo: ?");

        lbl_Tope.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Tope.setText("Tope: ?");

        lbl_Frente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Frente.setText("Frente: ?");

        lbl_Final.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Final.setText("Final: ?");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Pila - Cola");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Notación Infija");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArea_Enunciado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtFld_NotacionInfija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrll_TablaPila, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrll_TablaCola, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Frente)
                            .addComponent(lbl_Fondo)
                            .addComponent(lbl_Tope)
                            .addComponent(lbl_Final))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtArea_Enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl_Fondo)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Tope))
                    .addComponent(scrll_TablaPila, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrll_TablaCola, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl_Frente)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Final)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFld_NotacionInfija, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MostrarActionPerformed
        txtFld_NotacionInfija.setText(mostrarNotInf);
    }//GEN-LAST:event_btn_MostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Mostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Final;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_Frente;
    private javax.swing.JLabel lbl_Tope;
    private javax.swing.JScrollPane scrll_TablaCola;
    private javax.swing.JScrollPane scrll_TablaPila;
    private javax.swing.JTable tbl_Cola;
    private javax.swing.JTable tbl_Pila;
    private javax.swing.JTextArea txtArea_Enunciado;
    private javax.swing.JTextField txtFld_NotacionInfija;
    // End of variables declaration//GEN-END:variables
}
