package paqueteproducto;

public class pnl_GeneralizadoFinal extends javax.swing.JPanel {

    /**
     * Creates new form pnl_GeneralizadoFinal
     */
    public pnl_GeneralizadoFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Enunciado = new javax.swing.JLabel();
        txtArea_Enunciado = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(245, 245, 245));

        lbl_Enunciado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Enunciado.setForeground(new java.awt.Color(70, 70, 70));
        lbl_Enunciado.setText("Enunciado");

        txtArea_Enunciado.setEditable(false);
        txtArea_Enunciado.setBackground(new java.awt.Color(255, 255, 255));
        txtArea_Enunciado.setColumns(20);
        txtArea_Enunciado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtArea_Enunciado.setForeground(new java.awt.Color(80, 80, 80));
        txtArea_Enunciado.setLineWrap(true);
        txtArea_Enunciado.setRows(5);
        txtArea_Enunciado.setText("Se tiene dos Estructuras de datos, PILA que contiene una lista de variables y COLA que contiene una lista de coeficientes. Debe preparar un método que empleando las operaciones de PILAS Y COLAS, arme el POLINOMIO (cadena lineal) correspondiente en notación infija. Implementación: (a) En una sola clase main, (b) En una clase main con métodos en esa misma clase, (c) en una clase main con métodos en otra clase y (d) con Swing.");
        txtArea_Enunciado.setWrapStyleWord(true);
        txtArea_Enunciado.setAutoscrolls(false);
        txtArea_Enunciado.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtArea_Enunciado.setFocusable(false);
        txtArea_Enunciado.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtArea_Enunciado.setMinimumSize(new java.awt.Dimension(750, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_Enunciado, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArea_Enunciado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbl_Enunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtArea_Enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Enunciado;
    private javax.swing.JTextArea txtArea_Enunciado;
    // End of variables declaration//GEN-END:variables
}
