package paqueteproducto;

public class pnl_GeneralizadoSiguiente extends javax.swing.JPanel {

    /**
     * Creates new form pnl_GeneralizadoSiguiente
     */
    public pnl_GeneralizadoSiguiente() {
        initComponents();
        btnGrp_MO.add(rdBtn_MO1);
        btnGrp_MO.add(rdBtn_MO2);
        btnGrp_MO.add(rdBtn_MO3);
        
        btnGrp_ME.add(rdBtn_ME1);
        btnGrp_ME.add(rdBtn_ME2);
    }
    
    /**
     * Métodos que se pueden modificar
     */
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp_MO = new javax.swing.ButtonGroup();
        btnGrp_ME = new javax.swing.ButtonGroup();
        lbl_MenuOperadores = new javax.swing.JLabel();
        lbl_MenuExponentes = new javax.swing.JLabel();
        rdBtn_MO1 = new javax.swing.JRadioButton();
        rdBtn_MO2 = new javax.swing.JRadioButton();
        rdBtn_MO3 = new javax.swing.JRadioButton();
        rdBtn_ME1 = new javax.swing.JRadioButton();
        rdBtn_ME2 = new javax.swing.JRadioButton();
        lbl_Tamaño = new javax.swing.JLabel();
        btn_Definir = new javax.swing.JButton();
        lbl_Tamaño1 = new javax.swing.JLabel();
        textFld_Tamaño1 = new javax.swing.JTextField();
        btn_Definir1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtArea_Enunciado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtArea_Enunciado1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(245, 245, 245));

        lbl_MenuOperadores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_MenuOperadores.setForeground(new java.awt.Color(70, 70, 70));
        lbl_MenuOperadores.setText("Menú: Operadores");

        lbl_MenuExponentes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_MenuExponentes.setForeground(new java.awt.Color(70, 70, 70));
        lbl_MenuExponentes.setText("Menú: Exponentes");

        rdBtn_MO1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdBtn_MO1.setText("Operadores con patrón: + - + - + ...");

        rdBtn_MO2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdBtn_MO2.setText("Operadores aleatorios.");

        rdBtn_MO3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdBtn_MO3.setText("Introducir por teclado los operadores.");

        rdBtn_ME1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdBtn_ME1.setText("Exponentes descendentes con excepción al último.");

        rdBtn_ME2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdBtn_ME2.setText("Introducir por teclado  los exponentes.");

        lbl_Tamaño.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Tamaño.setForeground(new java.awt.Color(70, 70, 70));
        lbl_Tamaño.setText("Operador");

        btn_Definir.setText("DEFINIR");

        lbl_Tamaño1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Tamaño1.setForeground(new java.awt.Color(70, 70, 70));
        lbl_Tamaño1.setText("Exponente");

        textFld_Tamaño1.setColumns(10);
        textFld_Tamaño1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_Definir1.setText("DEFINIR");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Término n°?");

        txtArea_Enunciado.setEditable(false);
        txtArea_Enunciado.setBackground(new java.awt.Color(255, 255, 255));
        txtArea_Enunciado.setColumns(20);
        txtArea_Enunciado.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtArea_Enunciado.setForeground(new java.awt.Color(100, 100, 100));
        txtArea_Enunciado.setLineWrap(true);
        txtArea_Enunciado.setRows(5);
        txtArea_Enunciado.setText("Ingrese un exponente para cada varible del polinomio.");
        txtArea_Enunciado.setWrapStyleWord(true);
        txtArea_Enunciado.setAutoscrolls(false);
        txtArea_Enunciado.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtArea_Enunciado.setFocusable(false);
        txtArea_Enunciado.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtArea_Enunciado.setMinimumSize(new java.awt.Dimension(750, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Término n°?");

        txtArea_Enunciado1.setEditable(false);
        txtArea_Enunciado1.setBackground(new java.awt.Color(255, 255, 255));
        txtArea_Enunciado1.setColumns(20);
        txtArea_Enunciado1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtArea_Enunciado1.setForeground(new java.awt.Color(100, 100, 100));
        txtArea_Enunciado1.setLineWrap(true);
        txtArea_Enunciado1.setRows(5);
        txtArea_Enunciado1.setText("Seleccione el tipo de operador para cada término del polinomio.");
        txtArea_Enunciado1.setWrapStyleWord(true);
        txtArea_Enunciado1.setAutoscrolls(false);
        txtArea_Enunciado1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtArea_Enunciado1.setFocusable(false);
        txtArea_Enunciado1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtArea_Enunciado1.setMinimumSize(new java.awt.Dimension(750, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtn_MO1)
                            .addComponent(lbl_MenuOperadores)
                            .addComponent(rdBtn_ME2)
                            .addComponent(rdBtn_ME1)
                            .addComponent(lbl_MenuExponentes)
                            .addComponent(rdBtn_MO3)
                            .addComponent(rdBtn_MO2))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtArea_Enunciado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Tamaño1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Definir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFld_Tamaño1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Definir1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtArea_Enunciado1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_MenuOperadores)
                        .addGap(18, 18, 18)
                        .addComponent(rdBtn_MO1)
                        .addGap(18, 18, 18)
                        .addComponent(rdBtn_MO2)
                        .addGap(18, 18, 18)
                        .addComponent(rdBtn_MO3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Tamaño)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Definir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArea_Enunciado1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_MenuExponentes)
                        .addGap(18, 18, 18)
                        .addComponent(rdBtn_ME1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdBtn_ME2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Tamaño1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(textFld_Tamaño1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Definir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArea_Enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp_ME;
    private javax.swing.ButtonGroup btnGrp_MO;
    private javax.swing.JButton btn_Definir;
    private javax.swing.JButton btn_Definir1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_MenuExponentes;
    private javax.swing.JLabel lbl_MenuOperadores;
    private javax.swing.JLabel lbl_Tamaño;
    private javax.swing.JLabel lbl_Tamaño1;
    private javax.swing.JRadioButton rdBtn_ME1;
    private javax.swing.JRadioButton rdBtn_ME2;
    private javax.swing.JRadioButton rdBtn_MO1;
    private javax.swing.JRadioButton rdBtn_MO2;
    private javax.swing.JRadioButton rdBtn_MO3;
    private javax.swing.JTextField textFld_Tamaño1;
    private javax.swing.JTextArea txtArea_Enunciado;
    private javax.swing.JTextArea txtArea_Enunciado1;
    // End of variables declaration//GEN-END:variables
}
