package paqueteproducto;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Variables que se pueden modificar
     */
    private final Color cRojoOscuro = new Color(175, 33, 81);
    private final Color cRojoClaro = new Color(216, 47, 75);
    private final Color cOscuro = new Color(51, 51, 51);
    
    private pnl_Presentacion presentacion = new pnl_Presentacion();
    private pnl_Propuesto propuesto = new pnl_Propuesto();
    private pnl_Generalizado generalizado = new pnl_Generalizado();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        enlazarPanel(presentacion);
        lbl_IndicadorPresentacion.setBackground(cRojoOscuro);
        setLocationRelativeTo(null);
    }

    /**
     * Métodos que se pueden modificar
     */
    private void enlazarPanel(JPanel panel) {
        panel.setSize(850, 600);
        panel.setLocation(0, 0);

        pnl_Principal.removeAll();
        pnl_Principal.add(panel, BorderLayout.CENTER);
        pnl_Principal.revalidate();
        pnl_Principal.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Lateral = new javax.swing.JPanel();
        lbl_Inicio = new javax.swing.JLabel();
        lbl_Presentacion = new javax.swing.JLabel();
        lbl_IndicadorPresentacion = new javax.swing.JLabel();
        lbl_Problema = new javax.swing.JLabel();
        lbl_Propuesto = new javax.swing.JLabel();
        lbl_IndicadorPropuesto = new javax.swing.JLabel();
        lbl_Generalizado = new javax.swing.JLabel();
        lbl_IndicadorGeneralizado = new javax.swing.JLabel();
        lbl_LogoUNS = new javax.swing.JLabel();
        pnl_Principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Producto: Estructura de Datos - Pilas y Colas");
        setPreferredSize(new java.awt.Dimension(1040, 635));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Lateral.setBackground(new java.awt.Color(51, 51, 51));
        pnl_Lateral.setPreferredSize(new java.awt.Dimension(0, 0));
        pnl_Lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Inicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicioE.png"))); // NOI18N
        lbl_Inicio.setText(" Inicio");
        lbl_Inicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        pnl_Lateral.add(lbl_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 175, 50));

        lbl_Presentacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Presentacion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Presentacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Presentacion.setText("Presentación");
        lbl_Presentacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        lbl_Presentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Presentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_PresentacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_PresentacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_PresentacionMouseExited(evt);
            }
        });
        pnl_Lateral.add(lbl_Presentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 286, 170, 50));

        lbl_IndicadorPresentacion.setBackground(new java.awt.Color(51, 51, 51));
        lbl_IndicadorPresentacion.setText(" ");
        lbl_IndicadorPresentacion.setOpaque(true);
        pnl_Lateral.add(lbl_IndicadorPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 286, 6, 50));

        lbl_Problema.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Problema.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Problema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/problemaE.png"))); // NOI18N
        lbl_Problema.setText(" Problema");
        lbl_Problema.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        pnl_Lateral.add(lbl_Problema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, 175, 50));

        lbl_Propuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Propuesto.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Propuesto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Propuesto.setText("Propuesto");
        lbl_Propuesto.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        lbl_Propuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Propuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_PropuestoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_PropuestoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_PropuestoMouseExited(evt);
            }
        });
        pnl_Lateral.add(lbl_Propuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 422, 170, 50));

        lbl_IndicadorPropuesto.setBackground(new java.awt.Color(51, 51, 51));
        lbl_IndicadorPropuesto.setText(" ");
        lbl_IndicadorPropuesto.setOpaque(true);
        pnl_Lateral.add(lbl_IndicadorPropuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 422, 6, 50));

        lbl_Generalizado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Generalizado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Generalizado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Generalizado.setText("Generalizado");
        lbl_Generalizado.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        lbl_Generalizado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Generalizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_GeneralizadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_GeneralizadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_GeneralizadoMouseExited(evt);
            }
        });
        pnl_Lateral.add(lbl_Generalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 472, 170, 50));

        lbl_IndicadorGeneralizado.setBackground(new java.awt.Color(51, 51, 51));
        lbl_IndicadorGeneralizado.setText(" ");
        lbl_IndicadorGeneralizado.setOpaque(true);
        pnl_Lateral.add(lbl_IndicadorGeneralizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 472, 6, 50));

        lbl_LogoUNS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LogoUNS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoUNS.png"))); // NOI18N
        pnl_Lateral.add(lbl_LogoUNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 175, 200));

        getContentPane().add(pnl_Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 175, 600));

        pnl_Principal.setBackground(new java.awt.Color(245, 245, 245));
        pnl_Principal.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pnl_PrincipalLayout = new javax.swing.GroupLayout(pnl_Principal);
        pnl_Principal.setLayout(pnl_PrincipalLayout);
        pnl_PrincipalLayout.setHorizontalGroup(
            pnl_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        pnl_PrincipalLayout.setVerticalGroup(
            pnl_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void lbl_PresentacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PresentacionMouseClicked
        enlazarPanel(presentacion);
        lbl_IndicadorPresentacion.setBackground(cRojoOscuro);
        lbl_IndicadorPropuesto.setBackground(cOscuro);
        lbl_IndicadorGeneralizado.setBackground(cOscuro);

    }//GEN-LAST:event_lbl_PresentacionMouseClicked

    private void lbl_PropuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PropuestoMouseClicked
        enlazarPanel(propuesto);
        lbl_IndicadorPresentacion.setBackground(cOscuro);
        lbl_IndicadorPropuesto.setBackground(cRojoOscuro);
        lbl_IndicadorGeneralizado.setBackground(cOscuro);

    }//GEN-LAST:event_lbl_PropuestoMouseClicked

    private void lbl_GeneralizadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_GeneralizadoMouseClicked
        enlazarPanel(generalizado);

        lbl_IndicadorPresentacion.setBackground(cOscuro);
        lbl_IndicadorPropuesto.setBackground(cOscuro);
        lbl_IndicadorGeneralizado.setBackground(cRojoOscuro);
    }//GEN-LAST:event_lbl_GeneralizadoMouseClicked

    private void lbl_PresentacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PresentacionMouseEntered
        lbl_Presentacion.setOpaque(true);
        lbl_IndicadorPresentacion.setBackground(cRojoOscuro);
        lbl_Presentacion.setBackground(cRojoClaro);
    }//GEN-LAST:event_lbl_PresentacionMouseEntered

    private void lbl_PresentacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PresentacionMouseExited
        lbl_Presentacion.setOpaque(true);
        if (!presentacion.isDisplayable()) {
            lbl_IndicadorPresentacion.setBackground(cOscuro);
        }
        lbl_Presentacion.setBackground(cOscuro);

    }//GEN-LAST:event_lbl_PresentacionMouseExited

    private void lbl_PropuestoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PropuestoMouseEntered
        lbl_Propuesto.setOpaque(true);
        lbl_IndicadorPropuesto.setBackground(cRojoOscuro);
        lbl_Propuesto.setBackground(cRojoClaro);
    }//GEN-LAST:event_lbl_PropuestoMouseEntered

    private void lbl_PropuestoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PropuestoMouseExited
        lbl_Propuesto.setOpaque(true);
        if (!propuesto.isDisplayable()) {
            lbl_IndicadorPropuesto.setBackground(cOscuro);
        }    
        lbl_Propuesto.setBackground(cOscuro);

    }//GEN-LAST:event_lbl_PropuestoMouseExited

    private void lbl_GeneralizadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_GeneralizadoMouseEntered
        lbl_Generalizado.setOpaque(true);
        lbl_IndicadorGeneralizado.setBackground(cRojoOscuro);
        lbl_Generalizado.setBackground(cRojoClaro);
    }//GEN-LAST:event_lbl_GeneralizadoMouseEntered

    private void lbl_GeneralizadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_GeneralizadoMouseExited
        lbl_Generalizado.setOpaque(true);
        if (!generalizado.isDisplayable()) {
            lbl_IndicadorGeneralizado.setBackground(cOscuro);
        }         
        lbl_Generalizado.setBackground(cOscuro);
    }//GEN-LAST:event_lbl_GeneralizadoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Generalizado;
    private javax.swing.JLabel lbl_IndicadorGeneralizado;
    private javax.swing.JLabel lbl_IndicadorPresentacion;
    private javax.swing.JLabel lbl_IndicadorPropuesto;
    private javax.swing.JLabel lbl_Inicio;
    private javax.swing.JLabel lbl_LogoUNS;
    private javax.swing.JLabel lbl_Presentacion;
    private javax.swing.JLabel lbl_Problema;
    private javax.swing.JLabel lbl_Propuesto;
    private javax.swing.JPanel pnl_Lateral;
    private javax.swing.JPanel pnl_Principal;
    // End of variables declaration//GEN-END:variables
}
